# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "بلاگ محسن طهماسبی"
email: "moh53n@moh53n.net"
description: >- # this means to ignore newlines until "baseurl:"
  "بلاگ فنی محسن طهماسبی، علاقه مند به امنیت سایبری، شبکه و هر چیزی درباره کامپیوتر ها"
baseurl: "/blog-fa" # the subpath of your site, e.g. /blog
url: "https://moh53n.net" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: moh53n_fa
github_username:  moh53n

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.27.0"
minimal_mistakes_skin: "dark"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

locale: "fa"
rtl: true


author:
  name             : "محسن طهماسبی"
  avatar           : "/assets/img/me.jpg"
  bio              : "علاقه مند به امنیت سایبری، شبکه و هر چیزی درباره کامپیوتر ها"
  email            : "moh53n@moh53n.net"
  links:
    - label: "وب سایت"
      icon: "fas fa-fw fa-link"
      url: "https://moh53n.net"
    - label: "توییتر"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/moh53n_fa"
    - label: "گیت هاب"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/moh53n"


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false
      show_date: true

